server:
  port: 8001

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: service-edu
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/guli?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  #微服务 服务注册
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#开启熔断机制
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000

mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
  mapper-locations: classpath:com/shop/eduservice/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl