server:
  port: 8006

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: service-user
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/guli?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        max-idle: 5
        min-idle: 0
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 180000

mybatis-plus:
  mapper-locations: classpath:com/shop/user/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


wechat:
  open:
    appid: appid
    appsecret: appsecret
    redirecturl: redirecturl